---
- name: Install clients
  action: "{{ ansible_pkg_mgr }} name={{ openshift.common.service_type }}-clients state=present"
  when: not openshift.common.is_containerized | bool

- name: Pull CLI Image
  command: >
    docker pull {{ openshift.common.cli_image }}:{{ openshift_image_tag }}
  register: pull_result
  changed_when: "'Downloaded newer image' in pull_result.stdout"
  when: openshift.common.is_containerized | bool

- name: Copy client binaries/symlinks out of CLI image for use on the host
  openshift_container_binary_sync:
    image: "{{ openshift.common.cli_image }}"
    tag: "{{ openshift_image_tag }}"
  when: openshift.common.is_containerized | bool

- name: Reload facts to pick up installed OpenShift version
  openshift_facts:

- name: Install bash completion for oc tools
  action: "{{ ansible_pkg_mgr }} name=bash-completion state=present"
  when: not openshift.common.is_containerized | bool
